name: Generates Neorg tag

on:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        version:
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Plenary
        uses: actions/checkout@v2
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim
      - name: Install Treesitter
        uses: actions/checkout@v2
        with:
          repository: nvim-treesitter/nvim-treesitter
          path: nvim-treesitter
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: neovim
        with:
          neovim: true
          version: ${{ matrix.version }}
      - name: Run tag_gen
        run: make tag
      env:
        GITHUB_REPO: ${{ secrets.GITHUB_TOKEN }}
