name: Test

on: [push, pull_request]

jobs:
    lint:
        name: PlenaryBustedDirectory
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                path: neorg
            - uses: actions/checkout@v2
              with:
                repository: nvim-treesitter/nvim-treesitter
                path: nvim-treesitter
            - uses: actions/checkout@v2
              with:
                repository: nvim-lua/plenary.nvim
                path: plenary.nvim
            - name: Setup
              run: |
                  sudo apt-get update
                  sudo add-apt-repository ppa:neovim-ppa/unstable
                  sudo apt-get install neovim
            - name: Test
              run: |
                cd neorg
                nvim --headless --clean -u tests/custom_init.vim -c "PlenaryBustedDirectory . {minimal_init = 'tests/custom_init.vim' }"
